name: Apply Labels from Issues

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  apply-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get issue labels
        id: get_labels
        uses: octokit/request-action@v2
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.pull_request.issue_url.split('/').pop() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply labels to PR
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels
          labels: ${{ steps.get_labels.outputs.data.labels }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
